### ISSUE TITLE
First project setup.

### ISSUE THREAD

**Issue by blueberry1312** [blueberry1312/react-group-project#25]
Link to project repo: https://github.com/blueberry1312/react-group-project

Note: Two members group.

**Comment by julie-ify** [comment]
Hi @blueberry1312 and @kkolade,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly provide the link to the Kanban board, not repo

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by blueberry1312** [comment]
Link to Github project: https://github.com/blueberry1312/react-group-project/projects/1
Note: Two members group.

**Comment by Abenezer-Tilahun** [comment]
Hi @blueberry1312 @kkolade  
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ Good Job for provide the link to their GitHub project.
✔️ Good Job for Provide information about the number of people in their group
✔️ Good Job for Setup  React group project: set up your Kanban board
## Optional suggestions 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
